# Generated by Django 4.1.3 on 2022-12-01 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="courses",
            options={"verbose_name": "Курс", "verbose_name_plural": "Курсы"},
        ),
        migrations.AlterModelOptions(
            name="courseteachers",
            options={"verbose_name": "Учитель", "verbose_name_plural": "Учителя"},
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ("course", "num"),
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
        migrations.AlterModelOptions(
            name="news",
            options={"verbose_name": "Новость", "verbose_name_plural": "Новости"},
        ),
    ]
