# Generated by Django 4.1.3 on 2022-12-01 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_alter_courses_options_alter_courseteachers_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="courseteachers",
            options={
                "verbose_name": "Преподаватель",
                "verbose_name_plural": "Преподаватели",
            },
        ),
        migrations.AlterField(
            model_name="courses",
            name="cost",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=8, verbose_name="Цена"
            ),
        ),
        migrations.AlterField(
            model_name="courses",
            name="cover",
            field=models.CharField(
                default="no_image.svg", max_length=25, verbose_name="Лого"
            ),
        ),
        migrations.AlterField(
            model_name="courses",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
        ),
        migrations.AlterField(
            model_name="courses",
            name="deleted",
            field=models.BooleanField(default=False, verbose_name="Удален"),
        ),
        migrations.AlterField(
            model_name="courses",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="courses",
            name="name",
            field=models.CharField(max_length=256, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="courses",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
        ),
        migrations.AlterField(
            model_name="courseteachers",
            name="day_birth",
            field=models.DateField(verbose_name="Дата рождения"),
        ),
        migrations.AlterField(
            model_name="courseteachers",
            name="deleted",
            field=models.BooleanField(default=False, verbose_name="Удален"),
        ),
        migrations.AlterField(
            model_name="courseteachers",
            name="name_first",
            field=models.CharField(max_length=128, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="courseteachers",
            name="name_second",
            field=models.CharField(max_length=128, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mainapp.courses",
                verbose_name="Название курса",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="deleted",
            field=models.BooleanField(default=False, verbose_name="Удален"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="num",
            field=models.PositiveIntegerField(verbose_name="Номер урока"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="title",
            field=models.CharField(max_length=256, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
        ),
        migrations.AlterField(
            model_name="news",
            name="body",
            field=models.TextField(blank=True, null=True, verbose_name="Тело новости"),
        ),
        migrations.AlterField(
            model_name="news",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
        ),
        migrations.AlterField(
            model_name="news",
            name="deleted",
            field=models.BooleanField(default=False, verbose_name="Удален"),
        ),
        migrations.AlterField(
            model_name="news",
            name="preambule",
            field=models.CharField(max_length=1024, verbose_name="Короткое описание"),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(max_length=128, verbose_name="Заголовок"),
        ),
        migrations.AlterField(
            model_name="news",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
        ),
    ]
