# Generated by Django 4.1.3 on 2022-12-08 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mainapp", "0004_coursefeedback"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coursefeedback",
            options={"verbose_name": "feedback", "verbose_name_plural": "feedbacks"},
        ),
        migrations.AlterModelOptions(
            name="courses",
            options={"verbose_name": "course", "verbose_name_plural": "courses"},
        ),
        migrations.AlterModelOptions(
            name="courseteachers",
            options={"verbose_name": "teacher", "verbose_name_plural": "teachers"},
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ("course", "num"),
                "verbose_name": "lesson",
                "verbose_name_plural": "lessons",
            },
        ),
        migrations.AlterModelOptions(
            name="news",
            options={"verbose_name": "News", "verbose_name_plural": "News"},
        ),
        migrations.AlterField(
            model_name="coursefeedback",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mainapp.courses",
                verbose_name="Course",
            ),
        ),
        migrations.AlterField(
            model_name="coursefeedback",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="coursefeedback",
            name="deleted",
            field=models.BooleanField(default=False, verbose_name="deleted"),
        ),
        migrations.AlterField(
            model_name="coursefeedback",
            name="feedback",
            field=models.TextField(default="Без отзыва", verbose_name="feedback"),
        ),
        migrations.AlterField(
            model_name="coursefeedback",
            name="rating",
            field=models.SmallIntegerField(
                choices=[(5, "⭐⭐⭐⭐⭐"), (4, "⭐⭐⭐⭐"), (3, "⭐⭐⭐"), (2, "⭐⭐"), (1, "⭐")],
                default=5,
                verbose_name="rating",
            ),
        ),
        migrations.AlterField(
            model_name="coursefeedback",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="updated"),
        ),
        migrations.AlterField(
            model_name="coursefeedback",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="courses",
            name="cost",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=8, verbose_name="price"
            ),
        ),
        migrations.AlterField(
            model_name="courses",
            name="cover",
            field=models.CharField(
                default="no_image.svg", max_length=25, verbose_name="logo"
            ),
        ),
        migrations.AlterField(
            model_name="courses",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="courses",
            name="deleted",
            field=models.BooleanField(default=False, verbose_name="deleted"),
        ),
        migrations.AlterField(
            model_name="courses",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="courses",
            name="name",
            field=models.CharField(max_length=256, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="courses",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="updated"),
        ),
        migrations.AlterField(
            model_name="courseteachers",
            name="day_birth",
            field=models.DateField(verbose_name="date birth"),
        ),
        migrations.AlterField(
            model_name="courseteachers",
            name="deleted",
            field=models.BooleanField(default=False, verbose_name="Deleted"),
        ),
        migrations.AlterField(
            model_name="courseteachers",
            name="name_first",
            field=models.CharField(max_length=128, verbose_name="first name"),
        ),
        migrations.AlterField(
            model_name="courseteachers",
            name="name_second",
            field=models.CharField(max_length=128, verbose_name="last name"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mainapp.courses",
                verbose_name="Course name",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="deleted",
            field=models.BooleanField(default=False, verbose_name="deleted"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="num",
            field=models.PositiveIntegerField(verbose_name="lesson number"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="title",
            field=models.CharField(max_length=256, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="updated"),
        ),
        migrations.AlterField(
            model_name="news",
            name="body",
            field=models.TextField(blank=True, null=True, verbose_name="body"),
        ),
        migrations.AlterField(
            model_name="news",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="news",
            name="deleted",
            field=models.BooleanField(default=False, verbose_name="deleted"),
        ),
        migrations.AlterField(
            model_name="news",
            name="preambule",
            field=models.CharField(max_length=1024, verbose_name="short description"),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(max_length=128, verbose_name="header"),
        ),
        migrations.AlterField(
            model_name="news",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="updated"),
        ),
    ]
