# Generated by Django 4.1.3 on 2022-12-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0002_alter_user_age_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="age"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="users", verbose_name="avatar"
            ),
        ),
    ]
